### ISSUE TITLE
关于微信分享的问题

### ISSUE THREAD

**Issue by tappingcode** [backToNature/m-share#2]
您好，我想请教一下，在vue项目里面，如果要使用微信分享，Mshare.to('wx', config); 也是使用这个吗？那个微信的配置wxConfig(config)要在哪里执行或使用呢？

**Comment by backToNature** [comment]
使用wxConfig(config)首先需要确保当前页面为公众号页面，具备访问微信api的能力，也就是说得拿到```appId```，```timestamp```，```nonceStr```， ```signature```等参数之后再执行这个方法

**Comment by tappingcode** [comment]
> 使用wxConfig(config)首先需要确保当前页面为公众号页面，具备访问微信api的能力，也就是说得拿到`appId`，`timestamp`，`nonceStr`， `signature`等参数之后再执行这个方法

是在执行Mshare.to('wx', config);的点击事件里面使用吗

**Comment by backToNature** [comment]
> 是在执行Mshare.to('wx', config);的点击事件里面使用吗

不是，需要提前执行，建议在拿到相应的参数之后立即执行。
