### ISSUE TITLE
配置的config不起作用

### ISSUE THREAD

**Issue by codingJia** [backToNature/m-share#4]
从UC浏览器打开，点击分享，选择微信分享，config已经都进行了配置，但是无法获取config的数据，还是使用的默认config数据
还有就是，config中的desc无论在哪个分享中都没有起作用，就算配置了meta标签，分享出来得desc也是空的

**Comment by backToNature** [comment]
提供一下系统版本和UC浏览器的版本

**Comment by codingJia** [comment]
修改了下源码，改好了，不过好像uc浏览器分享得参数只能是在title，desc，link和image中选择三个配置，超出得一个不起作用，所以我舍弃了image，uc会默认截图来配置image

**Comment by backToNature** [comment]
hello，方便提个pr或者告知下哪部分有改动吗，多谢

**Comment by codingJia** [comment]
已提交pr
